services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - wordpress_data:/var/www/html:ro
    ports:
      - "80:80"
    networks:
      - docker_network
    depends_on:
      - wordpress

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    ports:
      - 9000
    networks:
      - docker_network
    env_file:
      - ../.env
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html/
  
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    ports:
      - 3306
    networks:
      - docker_network
    env_file:
      - ../.env
    volumes:
      - mariadb_data:/var/lib/mysql

networks:
  docker_network:

volumes:
  wordpress_data:
    name: wordpress_data
  mariadb_data:
    name: mariadb_data