services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - ./requirements/logs/nginx:/var/log/nginx
    ports:
      - "80:80"
    networks:
      - inception_network

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    # volumes:
    #   - ./requirements/wordpress:/var/www/html
    ports:
      - ":9090"
    networks:
      - inception_network
    env_file:
      - .env
  
  mariadb:
    container_name: mariadb
    build: ./requirements/wordpress
    ports:
      - ":9090"
    networks:
      - inception_network
    env_file:
      - .env

networks:
  wordpress_network: