services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    args:
      - SSL_CERT_PATH=${SSL_CERT_PATH}
      - SSL_KEY_PATH=${SSL_KEY_PATH}
    volumes:
      - wordpress_data:/var/www/html:ro
    ports:
      - "80:80"
    networks:
      - docker_network
    depends_on:
      - wordpress
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    ports:
      - 9000
    networks:
      - docker_network
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress_data:/var/www/html
  
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    ports:
      - 3306
    networks:
      - docker_network
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 6
      start_period: 5s

networks:
  docker_network:

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb